DEMO-34
Anii555/API_OnlineShop_backend pull request #3
Opened 2022-06-01 18:11 UTC by Anii555

Не без косяков, но всё равно запушу

2022-06-01 21:22 UTC, Corel-frim requested changes

2022-06-01 21:22 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return Cart.Products;
ToList еще надо(

2022-06-01 21:22 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return Cart.Products.Where(x=>x.ProductId == id);
А тут FirstOrDefault, и возвращаемый тип не коллекцию

2022-06-01 21:22 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +        public List<Product>? Get()
Так, давай теперь пойдем по REST-у:
Возвращаемый тип должен быть Task\<IActionResult> (у всех методов в контроллере)
А возврат результата должен быть через return Ok(Cart.Products); (это для примера, лучше Cart.Products вынести в переменную)

Почему именно так надо? Потому что, например, для Post запросов принято возвращать Created(createdItem) - так в ответе будет другой код ответа (204 Created), шо как бы ну правильно

2022-06-01 21:22 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +        public void Put(int id, [FromBody] int quantity)
Лучше quantity тоже делать по аналогии с id - чтобы они из пути приходили, а не из body, потому что у тебя так разделение логики: половина из одного места приходит, половина из другого

2022-06-01 21:22 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (Cart.Products.Any(x => x.ProductId == id))
Ну, собсна, обсудили (да же?)

2022-06-06 17:03 UTC, Corel-frim requested changes

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Cart.cs
> +        public static Dictionary<int, Product>? Products { get; set; }
Products не должен быть nullable (убери знак вопроса)

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +        Dictionary<int, Product>? Products = new Dictionary<int, Product>();
Удоли.

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Cart.cs
> -    public static class Cart
Верни

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +        public async Task<IActionResult> GetById(int id)
Метод тоже можно назвать "Get", конфликтов не будет (да и не совсем корректно указывать "ById", если у тебя id в аргументах идет)

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +        public async Task<IActionResult> Post(Product product)
Только нужно не целиком продукт брать, а только id его, и если уж хочется хранить продукты, то тогда в этом же месте и запрашивай продукт из бд

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return CreatedAtAction(nameof(GetById), new { id = product.ProductId}, product);
Не катит, надо всю корзину возвращать

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +        public async Task<IActionResult> GetById(int id)
А зачем тебе, кстати, получать по айдишнику предметы в корзине? Если данные нужны, то их из контроллера продуктов надо брать

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +
Тут должен быть код, который в корзину вообще закидывает хоть что-то

2022-06-06 17:03 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +    public class CartController : ControllerBase
Эх, вот бы из корзины можно было удалять (уменьшать кол-во) предметы... А чистить корзину одним действием - вообще огонь

2022-06-07 08:27 UTC, Corel-frim commented on API_OnlineShop_backend/API_OnlineShop_backend.csproj
> +    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.3.43" />
Убери, ты не используешь DynamoDB

2022-06-07 10:32 UTC, Anii555 commented on API_OnlineShop_backend/Cart.cs
> +        public static Dictionary<int, Product>? Products { get; set; }
✅

2022-06-07 10:33 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +        Dictionary<int, Product>? Products = new Dictionary<int, Product>();
А, перед публикацией забыла убрать, соре ✅

2022-06-07 10:33 UTC, Anii555 commented on API_OnlineShop_backend/Cart.cs
> -    public static class Cart
Аналогично ✅

2022-06-07 10:35 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +    public class CartController : ControllerBase
Угу, в описании к пушу же есть пометка "пока без put и delete"

2022-06-07 10:36 UTC, Anii555 commented on API_OnlineShop_backend/API_OnlineShop_backend.csproj
> +    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.3.43" />
✅

2022-06-12 18:33 UTC, Corel-frim requested changes

2022-06-12 18:33 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (!cart_item.Any(x => x.Key.ProductId == id))
Предлагаю следующим образом: делаешь переменную чуть выше через cart_item.FirstOrDefault
На этой строчке проверяешь ее на is null
А на 27 вовзращаешь Ok с этой переменной

Для чего так предлагаю: у тебя поиск по коллекции при таком варианте будет происходить всего 1 раз, а сейчас идет 2 раза

2022-06-12 18:33 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var cart_item = Cart.Products.FirstOrDefault(x => x.Key.ProductId == id);
Близко, но нужно из бд продукт брать, чтобы в корзину добавить, а не из корзины 😅 Но это место можешь оставить, чтобы проверять, вдруг предмет уже есть в корзине, и его уже не надо добавлять

2022-06-12 18:33 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return CreatedAtAction(nameof(Get), new { id = cart_item }, Cart.Products);
Сложна трудна ненада
Можно это на Created("product", id) заменить, но еще как вариант я бы предложил Accepted(), потому что у тебя на фронте данные от этого ответа никак не используются

2022-06-12 18:33 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var change_item = Cart.Products.FirstOrDefault(x => x.Key.ProductId == id).Key;
Предлагаю следующим образом проверить метод: добавляешь в корзину товар, открываешь вторую вкладку, в ней удаляешь товар из корзины, а затем в первой вкладке пробуешь поставить количество, скажем, 3

2022-06-12 18:33 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return Ok(Cart.Products);
Тут можно просто Ok(), Accepted() или NoContent(), все 3 будут приемлемы, объект при удалении обычно не возвращается

2022-06-12 18:33 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return Ok(Cart.Products);
Аналогично комментарию ниже

2022-06-15 08:19 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return Ok(Cart.Products);
✅

2022-06-15 08:19 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return Ok(Cart.Products);
✅

2022-06-15 08:47 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (!cart_item.Any(x => x.Key.ProductId == id))
✅

2022-06-15 10:09 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var cart_item = Cart.Products.FirstOrDefault(x => x.Key.ProductId == id);
✅

2022-06-15 10:14 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            return CreatedAtAction(nameof(Get), new { id = cart_item }, Cart.Products);
✅

2022-06-15 10:32 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var change_item = Cart.Products.FirstOrDefault(x => x.Key.ProductId == id).Key;
Так у меня фронт ещё не прописан (следующие задачи), как я проверю в таком случае? В консоль что-либо выводить..?

2022-06-15 12:39 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (id == null)
Но он никогда не будет null, разве что 0, но эту проверку надо в начало ставить

2022-06-15 12:40 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (cart_item.Key.ProductId != product_item.ProductId)
А если в корзине этого предмета не будет, то cart_item будет null?

2022-06-15 13:53 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (cart_item.Key.ProductId != product_item.ProductId)
Да

2022-06-15 13:54 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (cart_item.Key.ProductId != product_item.ProductId)
Типа просто cart_item.Key.ProductId != null в таком случае сделать?

2022-06-15 13:55 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var change_item = Cart.Products.FirstOrDefault(x => x.Key.ProductId == id).Key;
Можно через swagger запросы отправлять же(

2022-06-15 13:56 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (cart_item.Key != null)
Если предмет есть, то сообщить, что его нет? 😁

2022-06-15 15:55 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (id == null)
✅

2022-06-15 15:56 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            if (cart_item.Key != null)
Oops✅

2022-06-15 19:48 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
У тебя cart_item может быть null, и на это надо проверять в самом начале

2022-06-16 08:14 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
Там там же в if есть ИЛИ, или их местами поменять имеешь ввиду?

2022-06-16 12:07 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
Поменять местами И добавить проверку cart_item на null

2022-06-17 09:10 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
Низя словарь так проверять, поэтому по ключу проверку и задала 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/43905248/174267058-56fe3e67-aea2-4763-9021-e8ae2c79b8e0.png">

2022-06-17 09:11 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
Низя словарь так проверять, поэтому по ключу проверку и задала
<img width="664" alt="image" src="https://user-images.githubusercontent.com/43905248/174267169-15af63e2-f953-4b16-9548-e27d9a1ca7f5.png">

2022-06-17 09:12 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
Низя словарь так проверять, поэтому по ключу проверку и задала
<img width="628" alt="image" src="https://user-images.githubusercontent.com/43905248/174267484-ff39824a-16e4-4dbc-8964-00ac627ae484.png">

2022-06-17 09:14 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
Потому что ключ - это и есть корзинный объект Products, и если корзина пуста, то и cart_item.Keys будет null, отладчиком проверяла

2022-06-17 11:41 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +                if (product_item.ProductId != cart_item.Key.ProductId || cart_item.Key == null)
А, извиняюсь, это же структура( == default надо, вооот

2022-06-17 14:56 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var change_item = Cart.Products.FirstOrDefault(x => x.Key.ProductId == id).Key;
Ааа, точняк

2022-06-17 15:11 UTC, merged