DEMO-41
Anii555/API_OnlineShop_backend pull request #6
Opened 2022-07-07 21:06 UTC by Anii555

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +<<<<<<< HEAD
Это тут зачем?

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +<<<<<<< HEAD
И снова

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +=======
.

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +>>>>>>> DEMO-41
.

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        [HttpPost("login/{model}")]
Нельзя так

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        public async Task<IActionResult> Login(LoginViewModel model)
model нужно принимать через [FromBody]

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var product_item = _productRepository.GetAll().Result.FirstOrDefault(x => x.ProductId == id);
Что это еще за .Result? Его быть не должно

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityRoleController.cs
> +            _context.Add(new IdentityRole("simpleUser"));
Т.е. на каждый запрос будет добавляться новая роль? Выглядит не очень

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +            var users = _context.Users.ToList();
ToListAsync должно быть

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/RoleManagerController.cs
> +            return Ok(await _roleManager.Roles.ToListAsync());
Не стоит делать await чего-либо при передаче аргумента в метод, лучше вынести в отдельную переменную, и уже ее закидывать в метод

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/RoleManagerController.cs
> +            await _roleManager.CreateAsync(new IdentityRole { Name = "Admin", NormalizedName = "ADMIN" });
И, опять же, при каждом вызове будет каждый раз создаваться новая роль?

2022-07-09 12:30 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/UserManagerController.cs
> +            return Ok(_userManager.Users.ToList());
ToListAsync

2022-07-09 12:32 UTC, Corel-frim requested changes
И ждем библиотеку

2022-07-09 12:32 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/ProductController.cs
> +        [HttpGet("getAllProducts")]
Удоли лишний пробел

2022-07-09 12:32 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +builder.Services.AddControllersWithViews();
Нет, у тебя не должно быть WithViews, потому что вместо Views у тебя полноценный фронтенд

2022-07-09 12:38 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +<<<<<<< HEAD
Это не моё, у меня в коде этого нет. Вылезло при попытке запушить из VS, аля "исправить ветку" или типо того (не сработало, поэтому перепушила)

2022-07-09 12:38 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +<<<<<<< HEAD
<img width="240" alt="image" src="https://user-images.githubusercontent.com/43905248/178106122-0f0145d7-ce97-4dc1-912d-c56c9ccd1152.png">

2022-07-09 12:43 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +<<<<<<< HEAD
<img width="288" alt="image" src="https://user-images.githubusercontent.com/43905248/178106271-c514d99d-239b-4bc8-90d8-b9ac6e8bbe1a.png">

2022-07-09 12:47 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        public async Task<IActionResult> Login(LoginViewModel model)
✅

2022-07-09 12:48 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/ProductController.cs
> +        [HttpGet("getAllProducts")]
✅

2022-07-09 12:49 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/UserManagerController.cs
> +            return Ok(_userManager.Users.ToList());
✅

2022-07-09 12:50 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +            var users = _context.Users.ToList();
✅

2022-07-09 12:54 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var product_item = _productRepository.GetAll().Result.FirstOrDefault(x => x.ProductId == id);
Без него FirstOrDefault не пашет
<img width="628" alt="image" src="https://user-images.githubusercontent.com/43905248/178106627-a715e33e-4262-48d2-9783-ba752fca0b52.png">

2022-07-09 15:51 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +builder.Services.AddControllersWithViews();
Принято. Классы ViewModel тоже сносить?

2022-07-09 15:52 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/IdentityRoleController.cs
> +            _context.Add(new IdentityRole("simpleUser"));
Это я, видимо, хотела чтобы при запуске хотя бы что-то выводилось, т.к база пока пустая

2022-07-09 15:53 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/RoleManagerController.cs
> +            await _roleManager.CreateAsync(new IdentityRole { Name = "Admin", NormalizedName = "ADMIN" });
Это я, видимо, хотела чтобы при запуске хотя бы что-то выводилось, т.к база пока пустая

2022-07-09 18:54 UTC, Corel-frim requested changes

2022-07-09 18:54 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
>          [HttpPost("register/{model}")]
model здесь быть не должно

2022-07-09 18:54 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        [HttpPost("login/{model}")]
И здесь тоже

2022-07-09 18:54 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +            var users = _context.Users.ToListAsync();
А await?

2022-07-09 18:54 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/UserManagerController.cs
> +            return Ok(_userManager.Users.ToListAsync());
А await?

2022-07-09 19:05 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/UserManagerController.cs
> +            return Ok(_userManager.Users.ToListAsync());
✅

2022-07-09 19:07 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +            var users = _context.Users.ToListAsync();
✅

2022-07-09 19:12 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/RoleManagerController.cs
> +            return Ok(await _roleManager.Roles.ToListAsync());
✅

2022-07-09 19:34 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/IdentityRoleController.cs
> +            _context.Add(new IdentityRole("simpleUser"));
Исправила✅

2022-07-09 19:34 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/RoleManagerController.cs
> +            await _roleManager.CreateAsync(new IdentityRole { Name = "Admin", NormalizedName = "ADMIN" });
Исправила✅

2022-07-09 19:35 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +builder.Services.AddControllersWithViews();
Снесла✅

2022-07-09 21:44 UTC, Corel-frim requested changes

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var product_item = _productRepository.GetAll().Result.FirstOrDefault(x => x.ProductId == id);
Окей, т.е. ты собираешься выгрузить из бд абсолютно всю таблицу в оперативку, чтобы взять только одну запись?

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityRoleController.cs
> +            _context.Add(new IdentityRole("simpleUser"));
Оно все еще тут же... Если тебе нужно, чтобы роль была изначально в бд (и не добавлялась при каждом запросе), то нужно сделать добавление этой роли при миграции или при инициализации бд

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                //    return RedirectToAction("Index", "Home");
return Ok(result.User) (с result.User предположительно)

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                //var result = await _userManager.CreateAsync(user, Input.Password);
Что за Input.Password?

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            if (ModelState.IsValid)
Этой проверки быть не должно при использовании сервера как апи

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                //    foreach (var error in result.Errors)
Не нужно

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            if (ModelState.IsValid)
Этой проверки быть не должно

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        [HttpPost("login/{model}")]
model приходит из body - в запросе ее требовать уже не надо

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                //        return Redirect(model.ReturnUrl);
Не нужно никуда редиректить, тут должен возвращаться токен

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                //        return RedirectToAction("Index", "Home");
Аналогично

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                //    ModelState.AddModelError("", "Неправильный логин и (или) пароль");
Не нужно использовать ModelState

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            return RedirectToAction("Index", "Home");
Просто Accepted

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityRoleController.cs
> +            return Ok(await _context.Roles.ToListAsync());
Не стоит делать await в аргументах

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +            if (ModelState.IsValid)
Не должно быть

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        [HttpPost("create/{model}")]
Не нужен model

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +                //    return RedirectToAction("Index");
Не надо редиректов

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        public async Task<IActionResult> Edit(string id)
А что тут, собственно, меняется вообще?

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        [HttpPut("{model}")]
Нет

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +            if (ModelState.IsValid)
Не надо

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +                        foreach (var error in result.Errors)
Не нужно

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +                        return RedirectToAction("Index");
Не редирект

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        public async Task<IActionResult> Edit([FromBody] IdentityUser model)
Это Edit или ChangeEmail?

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        [HttpPost("{id}")]
Никаких Post для Delete

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +            return RedirectToAction("Index");
Нет

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/RoleManagerController.cs
> +    public class RoleManagerController : ControllerBase
Не имеет смысла, удаляй

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/UserManagerController.cs
> +    public class UserManagerController : ControllerBase
Не имеет смысла

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var product_item = _productRepository.GetAll().Result.FirstOrDefault(x => x.ProductId == id);
У тебя есть другой метод в репозитории для этого

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityRoleController.cs
> +    public class IdentityRoleController : ControllerBase
Не имеет смысла, к слову

2022-07-09 21:44 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +builder.Services.AddControllersWithViews();
А WithViews еще тут

2022-07-09 21:44 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/DB_Context/OrderDetail.cs
> +
Пустая строка зачем-то

2022-07-09 21:44 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/DataSeed.cs
> +        public static async Task SeedDataAsync(NorthwindContext context, Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager)
Раз уж используется Seed, то надо делать по-человечески, через Seed в бд

2022-07-09 21:44 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/ProductRepository.cs
> +            var prod = await _context.Products.FirstOrDefaultAsync(x => x.ProductId == id);
А сокращать-то пару букв зачем?(

2022-07-10 12:09 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                //    foreach (var error in result.Errors)
Снесла else полностью✅

2022-07-10 12:10 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        [HttpPost("login/{model}")]
✅

2022-07-10 12:11 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        [HttpPost("create/{model}")]
✅

2022-07-10 12:13 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        [HttpPut("{model}")]
✅

2022-07-10 12:14 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        [HttpPost("{id}")]
✅

2022-07-10 12:16 UTC, Anii555 commented on ProductsLibrary/ProductsLibrary/DB_Context/OrderDetail.cs
> +
✅

2022-07-10 17:34 UTC, Corel-frim requested changes

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Cart.cs
> +using ProductsLibrary;
Надо убрать

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        public IActionResult Register()
Но если тут ничего не происходит, то зачем этот метод?

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            return Ok(model);
Так если не result.Succeeded, то тут ошибка будет же, а не Ok

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            return Ok(model);
До сюда код не дойдет

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        [HttpGet]
Get на регистрации быть не должно

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +        [HttpPost]
Пустой Post, который логаутит, не очень корректно делать (имеется ввиду без приписок к пути)

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/CartController.cs
> +            var product_item = _productRepository.GetId(id).Result;
Никаких .Result, должен быть await

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/Identity/IdentityUserController.cs
> +        public IdentityUserController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
Не нужен

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
>  var MyAllowSpecificOrigins = "_myAllowSpecificOrigins";
const string, а не var

2022-07-10 17:34 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +builder.Services.AddScoped<ProductRepository, ProductRepository>();
Достаточно просто `builder.Services.AddScoped<ProductRepository>();`

2022-07-10 17:34 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/ProductRepository.cs
> +    public class ProductRepository : IdentityDbContext<IdentityUser, IdentityRole, string> //Guid
Тогда уж long хотя бы, но никак не string

2022-07-10 17:34 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/ProductRepository.cs
> +            if (products == null)
А что эта проверка дает вместо обычного return products?
И да, products - множественное число, а тут только 1

2022-07-12 09:44 UTC, Corel-frim requested changes

2022-07-12 09:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            return Ok(model);
но ты не удалила(

2022-07-12 09:44 UTC, Corel-frim commented on DropTables.sql
> +﻿EXEC sp_MSforeachtable @command1 = "DROP TABLE ?"
Лучше такое не держать в репозитории, чисто на всякий случай :D

2022-07-12 10:18 UTC, Corel-frim requested changes

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            if (result.Succeeded)
Пустую строку между var и if надо

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            }
И перед return всегда

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +                return Ok(result);
И перед return всегда

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            User user = new User { Email = model.Email, UserName = model.Email };
var

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            var result =
Не переноси на новую строку, 120 символов не настолько критично соблюдать

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            if (result.Succeeded)
Пустая строка перед

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            if (result.Succeeded)
Можно, кстати, на тернарник переделать, если интересно

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController .cs
> +            return Accepted();
Пустая строка

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Cart.cs
> +using ProductsLibrary;
Так это, а где?

2022-07-12 10:18 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +//builder.Services.AddIdentityCore<NorthwindContext>();
Не оставляй так

2022-07-12 10:18 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/DataSeed.cs
> +        public static async Task SeedDataAsync(NorthwindContext context, Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager)
Можно удалить, кстати, у тебя же все равно регистрация есть

2022-07-12 10:18 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/ProductRepository.cs
> +    public class ProductRepository : IdentityDbContext<IdentityUser, IdentityRole, string> //Guid
Эй, алло(

2022-07-12 12:12 UTC, Corel-frim requested changes

2022-07-12 12:12 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return Ok(result);
Тут тоже строку надо

2022-07-12 12:16 UTC, Corel-frim approved these changes

2022-07-12 12:17 UTC, merged