DEMO-42
Anii555/API_OnlineShop_backend pull request #8
Opened 2022-07-13 17:07 UTC by Anii555

2022-07-14 07:50 UTC, Corel-frim requested changes

2022-07-14 07:50 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return StatusCode(StatusCodes.Status500InternalServerError);
Што.

2022-07-14 07:50 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +{
Выровните, пожалуйста

2022-07-14 07:50 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +        //ValidAudience = builder.Configuration["jwt: validaudience"],
Опять закомментированный код?

2022-07-14 07:50 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +.AddJwtBearer(options =>
Если так делать, то надо перенести сразу после скобочки предыдущей

2022-07-14 13:22 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +        //ValidAudience = builder.Configuration["jwt: validaudience"],
Никак нет✅

2022-07-14 15:49 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return StatusCode(StatusCodes.Status500InternalServerError);
✅

2022-07-14 15:57 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +{
Ctrl k+d(f) не выравнивает..

2022-07-14 16:11 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +{
Как будто там скобка где-то лишняя, но так было в гайде + по-другому компилятор ругается..

2022-07-16 15:48 UTC, Corel-frim requested changes

2022-07-16 15:48 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -            }
Верни. Проверка правильная, неверный только return

2022-07-18 14:31 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -            }
✅

2022-07-18 14:33 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +.AddJwtBearer(options =>
✅

2022-07-18 15:58 UTC, Corel-frim requested changes
А токен-то при авторизации где?

2022-07-19 20:11 UTC, Corel-frim requested changes

2022-07-19 20:11 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/Migrations/20220719155106_NewMigration.cs
> +    public partial class NewMigration : Migration
Странное название, да и оно не нужно, потому что Password не должно быть в бд

2022-07-19 20:11 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
>          public async Task<IActionResult> Login([FromBody] User model)
Здесь тоже должна быть модель как с регистрацией

2022-07-19 20:11 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var result = await _signInManager.CheckPasswordSignInAsync(model, model.PasswordHash, false);
Никаких передач хэша на проверку пароля

2022-07-19 20:11 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return BadRequest("Пользователь с таким именем уже существует");
А лучше вернуть Conflict (409 код), только перед этим проверить пароль, и если он совпадает, то авторизовать пользователя вместо того, чтобы заставлять его регистрироваться, когда он уже

2022-07-19 20:11 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
Там внизу (return BadRequest(model)) нельзя возвращать model, т.к. тебе и так его прислали с фронта. Если хочешь хоть что-то вернуть - лучше верни список ошибок

2022-07-19 20:11 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +using Microsoft.AspNetCore.Authentication.JwtBearer;
Тут бы лишние юзинги почистить не помешало

2022-07-19 20:11 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/Models/RegisterModel.cs
> +        public string Password { get; set; }
Пустую строку между свойствами

2022-07-19 20:18 UTC, Anii555 commented on ProductsLibrary/ProductsLibrary/Models/RegisterModel.cs
> +        public string Password { get; set; }
✅

2022-07-19 20:18 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +using Microsoft.AspNetCore.Authentication.JwtBearer;
✅

2022-07-19 21:21 UTC, Anii555 commented on ProductsLibrary/ProductsLibrary/Migrations/20220719155106_NewMigration.cs
> +    public partial class NewMigration : Migration
✅

2022-07-20 09:13 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var result = await _signInManager.CheckPasswordSignInAsync(model, model.PasswordHash, false);
✅

2022-07-20 14:28 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
>          public async Task<IActionResult> Login([FromBody] User model)
✅

2022-07-20 14:30 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
✅

2022-07-20 15:59 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return BadRequest("Пользователь с таким именем уже существует");
✅

2022-07-20 16:18 UTC, Corel-frim requested changes

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var user = new User { UserName = model.Login, SecurityStamp = Guid.NewGuid().ToString() };
Создание нового пользователя должно быть только в случае, если существующего точно нет (перенеси это на после if)

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var check_pass = await _signInManager.CheckPasswordSignInAsync(user, model.Password, false);
Пользователя не существует в бд

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            if (userExists != null && check_pass.Succeeded)
Проверка пароля должна быть только если пользователь есть в бд, и если он существует, его нужно авторизовать, а не выкидывать ошибку

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
>              var result = await _userManager.CreateAsync(user, model.Password);
А если пользователь существует, но пароль при регистрации ввели не тот, что при прошлой, то снова будет создан пользователь

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -        [ValidateAntiForgeryToken]
Ну вот

2022-07-20 16:18 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/Models/LoginModel.cs
> +    public class LoginModel
В чем отличие от RegisterModel?

2022-07-20 16:18 UTC, Corel-frim commented on ProductsLibrary/ProductsLibrary/Models/RegisterModel.cs
> +    public class RegisterModel
В чем отличие от LoginModel?

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                foreach (var userRole in userRoles)
Роли пока не нужны

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                    token = new JwtSecurityTokenHandler().WriteToken(token),
Никаких new внутри new

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +
Пустую строку можно убрать

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                //var authSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JWT: SecretKey"]));
КХЕ-КХЕМ

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +        {
А точно вторая подряд нужна?

2022-07-20 16:18 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +                Reference = new OpenApiReference
Ну хоть отформатируй, что ли

2022-07-20 16:38 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -        [ValidateAntiForgeryToken]
✅

2022-07-20 16:39 UTC, Anii555 commented on ProductsLibrary/ProductsLibrary/Models/LoginModel.cs
> +    public class LoginModel
✅

2022-07-20 16:39 UTC, Anii555 commented on ProductsLibrary/ProductsLibrary/Models/RegisterModel.cs
> +    public class RegisterModel
✅

2022-07-20 16:40 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                foreach (var userRole in userRoles)
✅

2022-07-20 16:40 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +
✅

2022-07-20 16:41 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                //var authSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JWT: SecretKey"]));
✅-✅

2022-07-20 16:51 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var user = new User { UserName = model.Login, SecurityStamp = Guid.NewGuid().ToString() };
✅

2022-07-20 16:54 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +        {
<img width="391" alt="image" src="https://user-images.githubusercontent.com/43905248/180039532-06fb17d5-af62-4077-9660-3f20fe9465bc.png">
Точно

2022-07-20 16:56 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +                Reference = new OpenApiReference
Повторяю, ctrl + k + d на этих кусках кода не работают, в прошлый раз я вручную форматировала к более менее читабельному виду

2022-07-20 16:57 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +        {
Без них ругается

2022-07-20 17:48 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
>              var result = await _userManager.CreateAsync(user, model.Password);
✅

2022-07-20 17:48 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            if (userExists != null && check_pass.Succeeded)
✅

2022-07-20 17:48 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var check_pass = await _signInManager.CheckPasswordSignInAsync(user, model.Password, false);
✅

2022-07-20 18:01 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                    token = new JwtSecurityTokenHandler().WriteToken(token),
✅

2022-07-20 18:01 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -        [ValidateAntiForgeryToken]
Описала её бесполезность в ТГ

2022-07-21 12:44 UTC, Corel-frim requested changes

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return BadRequest("Аккаунт с таким логином уже существует.");
return Conflict

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var user = new User { UserName = model.Login, SecurityStamp = Guid.NewGuid().ToString() };
Перенеси это после if

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                    return await Login(new RegisterModel { Login = model.Login, Password = model.Password });
Вынеси общую часть с логина в отдельный метод, который будешь вызывать и здесь, и в Login

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        public async Task<IActionResult> Login([FromBody] RegisterModel model)
Почему RegisterModel в Login? Надо переименовать класс в AuthModel, например

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                    return await Login(new RegisterModel { Login = model.Login, Password = model.Password });
Зачем создавать новую модель RegisterModel, передавая туда все поля из уже существующего RegisterModel?

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var result = await _signInManager.CheckPasswordSignInAsync(userExists, model.Password, false);
А если userExists совсем не Exists?

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -                claims: authClaims
Верни клеймы

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +        {
Хорошо

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +                    Type = ReferenceType.SecurityScheme,
Еще отступ

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +                    Id = "Bearer"
Еще отступ

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +                },
Не надо отступ

2022-07-21 12:44 UTC, Corel-frim commented on API_OnlineShop_backend/Program.cs
> +                new string[] {}
Не надо отступ

2022-07-21 13:07 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return BadRequest("Аккаунт с таким логином уже существует.");
✅

2022-07-21 13:08 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        public async Task<IActionResult> Login([FromBody] RegisterModel model)
✅

2022-07-21 13:09 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                    return await Login(new RegisterModel { Login = model.Login, Password = model.Password });
✅

2022-07-21 13:28 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var user = new User { UserName = model.Login, SecurityStamp = Guid.NewGuid().ToString() };
А еще SecurityStamp нельзя вручную задавать

2022-07-21 13:28 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +                },
✅

2022-07-21 13:28 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +                new string[] {}
✅

2022-07-21 13:28 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +                    Type = ReferenceType.SecurityScheme,
✅

2022-07-21 13:28 UTC, Anii555 commented on API_OnlineShop_backend/Program.cs
> +                    Id = "Bearer"
✅

2022-07-21 13:33 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -                claims: authClaims
✅

2022-07-21 13:34 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var user = new User { UserName = model.Login, SecurityStamp = Guid.NewGuid().ToString() };
✅

2022-07-21 13:51 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            var result = await _signInManager.CheckPasswordSignInAsync(userExists, model.Password, false);
✅

2022-07-21 14:06 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                    return await Login(new RegisterModel { Login = model.Login, Password = model.Password });
✅

2022-07-21 15:01 UTC, Corel-frim requested changes

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return await Auth(userExists, model);
Нет return Conflict

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        public async Task<IActionResult> Auth([FromBody] User userExists, AuthModel model)
private

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        public async Task<IActionResult> Auth([FromBody] User userExists, AuthModel model)
Тут скорее нужно авторизовать пользователя только (вернуть токен), а не целиком ответ от сервера генерировать

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                foreach (var userRole in userRoles)
.

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                var userRoles = await _userManager.GetRolesAsync(userExists);
Роли все еще не нужны

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            //если пароль не совпадает, то
Пустая строка после кавычки

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        public async Task<IActionResult> Auth([FromBody] User userExists, AuthModel model)
Лучше здесь переименовать userExists в просто user

2022-07-21 15:01 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            return Conflict("Аккаунт с таким логином уже существует.");
Хороший ответ при попытке войти в аккаунт

2022-07-21 15:51 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        public async Task<IActionResult> Auth([FromBody] User userExists, AuthModel model)
✅

2022-07-21 15:51 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return await Auth(userExists, model);
В Auth() же есть

2022-07-21 15:52 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                var userRoles = await _userManager.GetRolesAsync(userExists);
✅

2022-07-21 15:54 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            //если не существует, то
✅

2022-07-21 15:54 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            //если пароль не совпадает, то
✅

2022-07-21 15:55 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        public async Task<IActionResult> Auth([FromBody] User userExists, AuthModel model)
✅

2022-07-21 15:55 UTC, Anii555 commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            return Conflict("Аккаунт с таким логином уже существует.");
✅

2022-07-21 16:39 UTC, Corel-frim requested changes

2022-07-21 16:39 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> -            var result = await _signInManager.CheckPasswordSignInAsync(userExists, model.Password, false);
Верни

2022-07-21 16:39 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            return Ok(new
return stringToken должно быть

2022-07-21 16:39 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +            return Ok(new
Без Ok и ему подобных

2022-07-21 16:39 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                var check_pass = await _signInManager.CheckPasswordSignInAsync(userExists, model.Password, false);
Нет.

2022-07-21 16:40 UTC, Corel-frim requested changes

2022-07-21 16:40 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +        private async Task<IActionResult> Auth(User user, AuthModel model)
Возвращаемый тип не тот

2022-07-21 16:41 UTC, Corel-frim requested changes

2022-07-21 16:41 UTC, Corel-frim commented on API_OnlineShop_backend/Controllers/AccountController.cs
> +                return Conflict("Неверный логин или пароль. Повторите попытку.");
Это не Conflict

2022-07-21 18:28 UTC, Corel-frim approved these changes
Норм, пойдет

2022-07-21 18:28 UTC, merged